### ISSUE TITLE
Doesn't seem to work with flake8 3.2.0

### ISSUE THREAD

**Issue by dopplershift** [zheller/flake8-quotes#48] opened 2016-11-19 21:10 UTC
I was doing some testing with flake8-quotes (to see if it would work with pytest-flake8), and noticed that flake8-quotes doesn't seem to recognize errors I added. It turns out this is a problem with using flake8 3.2.0. The errors are found just fine if I roll back to flake8 3.0.4.

**Comment by twolfson** [comment] 2016-11-19 23:56
I'm unable to reproduce this issue. I set up a new virtual environment and verified tests passed in both scenarios:

```bash
# In the context of `flake8-quotes` repo
# Create new virtual environment
mkvirtualenv flake8-quotes-flake8-3.2

# Install flake8 and our repo
pip install flake8==3.2.0
python setup.py develop

# Run our tests
./test.sh
# ...
# Ran 10 tests in 0.148s
# OK

# Perform same actions but with `flake8==3.0.4` in another virtual env
```

Can you provide us a sample of code that passes in 3.0.4 but not in 3.2.0?

**Comment by dopplershift** [comment] 2016-11-20 21:54
So more detail--I'm seeing this problem on:
- Travis CI running Linux (Ubuntu) using system python and packages installed using pip
- My local OSX (10.12.1) running Anaconda Python; I see failures with both conda-forge packages and pip-installed packages

I'm currently unable to get an error with flake8 3.2.0 with even the simplest `test.py` file:
```python
s = "bad string"
```
Simply installing 3.0.4 is enough to get back to working; it looks like flake8 3.1 is does not work either. Here's the verbose output when it works (flake8 3.0.4):
```
>flake8 --isolated -j 1 --disable-noqa -v test.py
flake8.plugins.manager    MainProcess    241 INFO     Loading entry-points for "flake8.extension".
flake8.plugins.manager    MainProcess    281 INFO     Loading entry-points for "flake8.listen".
flake8.plugins.manager    MainProcess    282 INFO     Loading entry-points for "flake8.report".
flake8.plugins.manager    MainProcess    282 INFO     Loading plugin "pycodestyle.comparison_type" from entry-point.
flake8.plugins.manager    MainProcess    289 INFO     Loading plugin "pycodestyle.missing_whitespace_after_import_keyword" from entry-point.
flake8.plugins.manager    MainProcess    289 INFO     Loading plugin "pycodestyle.imports_on_separate_lines" from entry-point.
flake8.plugins.manager    MainProcess    289 INFO     Loading plugin "pycodestyle.continued_indentation" from entry-point.
flake8.plugins.manager    MainProcess    289 INFO     Loading plugin "pycodestyle.maximum_line_length" from entry-point.
flake8.plugins.manager    MainProcess    289 INFO     Loading plugin "pycodestyle.python_3000_not_equal" from entry-point.
flake8.plugins.manager    MainProcess    289 INFO     Loading plugin "pycodestyle.trailing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    289 INFO     Loading plugin "F" from entry-point.
flake8.plugins.manager    MainProcess    305 INFO     Loading plugin "pycodestyle.whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.python_3000_has_key" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.comparison_negative" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.python_3000_raise_comma" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.python_3000_backticks" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.indentation" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.tabs_or_spaces" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.module_imports_on_top_of_file" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.missing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.whitespace_around_named_parameter_equals" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.explicit_line_join" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.whitespace_around_comma" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.whitespace_before_parameters" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.missing_whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.compound_statements" from entry-point.
flake8.plugins.manager    MainProcess    306 INFO     Loading plugin "pycodestyle.trailing_blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "pycodestyle.extraneous_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "pycodestyle.whitespace_around_keywords" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "pycodestyle.tabs_obsolete" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "pycodestyle.break_around_binary_operator" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "pycodestyle.whitespace_before_comment" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "pycodestyle.comparison_to_singleton" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "Q000" from entry-point.
flake8.plugins.manager    MainProcess    307 INFO     Loading plugin "C90" from entry-point.
flake8.plugins.manager    MainProcess    308 INFO     Loading plugin "default" from entry-point.
flake8.plugins.manager    MainProcess    308 INFO     Loading plugin "quiet-filename" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "pylint" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "quiet-nothing" from entry-point.
flake8.checker            MainProcess    310 INFO     Making checkers
flake8.checker            MainProcess    312 INFO     Checking 1 files
flake8.processor          MainProcess    313 WARNING  Plugin requested optional parameter "builtins" but this is not an available parameter.
flake8.main.application   MainProcess    313 INFO     Finished running
flake8.main.application   MainProcess    313 INFO     Reporting errors
test.py:1:5: Q000 Remove bad quotes.
flake8.main.application   MainProcess    314 INFO     Found a total of 1 violations and reported 1
```

and when it doesn't work (flake8 3.2.0):
```
>flake8 --isolated -j 1 --disable-noqa -v test.py
flake8.plugins.manager    MainProcess    263 INFO     Loading entry-points for "flake8.extension".
flake8.plugins.manager    MainProcess    303 INFO     Loading entry-points for "flake8.listen".
flake8.plugins.manager    MainProcess    303 INFO     Loading entry-points for "flake8.report".
flake8.plugins.manager    MainProcess    303 INFO     Loading plugin "pycodestyle.comparison_type" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "pycodestyle.missing_whitespace_after_import_keyword" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "pycodestyle.imports_on_separate_lines" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "pycodestyle.continued_indentation" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "pycodestyle.maximum_line_length" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "pycodestyle.python_3000_not_equal" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "pycodestyle.trailing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    309 INFO     Loading plugin "F" from entry-point.
flake8.plugins.manager    MainProcess    328 INFO     Loading plugin "pycodestyle.whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    328 INFO     Loading plugin "pycodestyle.python_3000_has_key" from entry-point.
flake8.plugins.manager    MainProcess    328 INFO     Loading plugin "pycodestyle.comparison_negative" from entry-point.
flake8.plugins.manager    MainProcess    328 INFO     Loading plugin "pycodestyle.python_3000_raise_comma" from entry-point.
flake8.plugins.manager    MainProcess    328 INFO     Loading plugin "pycodestyle.blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    328 INFO     Loading plugin "pycodestyle.python_3000_backticks" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.indentation" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.tabs_or_spaces" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.module_imports_on_top_of_file" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.missing_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.whitespace_around_named_parameter_equals" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.explicit_line_join" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.whitespace_around_comma" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.whitespace_before_parameters" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.missing_whitespace_around_operator" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.compound_statements" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.trailing_blank_lines" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.extraneous_whitespace" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.whitespace_around_keywords" from entry-point.
flake8.plugins.manager    MainProcess    329 INFO     Loading plugin "pycodestyle.tabs_obsolete" from entry-point.
flake8.plugins.manager    MainProcess    330 INFO     Loading plugin "pycodestyle.break_around_binary_operator" from entry-point.
flake8.plugins.manager    MainProcess    330 INFO     Loading plugin "pycodestyle.whitespace_before_comment" from entry-point.
flake8.plugins.manager    MainProcess    330 INFO     Loading plugin "pycodestyle.comparison_to_singleton" from entry-point.
flake8.plugins.manager    MainProcess    330 INFO     Loading plugin "Q000" from entry-point.
flake8.plugins.manager    MainProcess    331 INFO     Loading plugin "C90" from entry-point.
flake8.plugins.manager    MainProcess    331 INFO     Loading plugin "default" from entry-point.
flake8.plugins.manager    MainProcess    332 INFO     Loading plugin "quiet-filename" from entry-point.
flake8.plugins.manager    MainProcess    332 INFO     Loading plugin "pylint" from entry-point.
flake8.plugins.manager    MainProcess    332 INFO     Loading plugin "quiet-nothing" from entry-point.
flake8.checker            MainProcess    334 INFO     Making checkers
flake8.checker            MainProcess    336 INFO     Checking 1 files
flake8.processor          MainProcess    337 WARNING  Plugin requested optional parameter "builtins" but this is not an available parameter.
flake8.main.application   MainProcess    337 INFO     Finished running
flake8.main.application   MainProcess    337 INFO     Reporting errors
flake8.main.application   MainProcess    337 INFO     Found a total of 1 violations and reported 0
```
Based on that output, it looks to me like it finds the error but fails to report it. Both were running out of my home directory at this point with no configuration AFAICT (and I did my best to tell it to ignore any config.)

**Comment by dopplershift** [comment] 2016-11-20 22:00
Ah, I think this is probably the culprit:
https://gitlab.com/pycqa/flake8/issues/257

**Comment by twolfson** [comment] 2016-11-20 22:50
Ah, word. Nice catch and research. Going to close this issue as it looks like it's been resolved and should be released soon

https://gitlab.com/pycqa/flake8/merge_requests/148

https://gitlab.com/pycqa/flake8/commit/a981fe34ed5d02c762e40e1ed2d6f309290035b3

**Closed by twolfson** 2016-11-20 22:50 UTC
